[book]
title = "How I Made Your Machine"
description = "HIMYM - A Coding Style Guide"
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/kstonekuan/how-i-made-your-machine"
additional-css = ["theme/language-tabs.css"]
additional-js = ["theme/language-tabs.js"]
default-theme = "rust"
preferred-dark-theme = "ayu"

[preprocessor.language-tabs]
command = "./target/debug/mdbook-language-tabs-preprocessor"
renderer = ["html"]
